services:
  jekyll:
    platform: linux/arm64
    image: jekyll/jekyll:pages
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --host 0.0.0.0 --port 4000 --livereload
    environment:
      - JEKYLL_ENV=development
